INSERT INTO gamesearcher.games (gameName, gameDesc, gameConsoles, gamePlayers, gameCoop, gameGenres, gameReleaseDate, gameDeveloper, gamePublisher,
gameFrontArtUrl, gameBackArtUrl, gameLogoArtUrl, gameDevLogoArtUrl, gamePrice, gameDiscount) VALUES
(
'007: The World is not Enough', '', 'PS;', 1, false, 'Shooter;', STR_TO_DATE('11/08/2000', '%m/%d/%Y'), 'Black Ops Entertainment', /*https://stackoverflow.com/a/9907257/8480874*/
'Electronic Arts', 'http://thegamesdb.net/banners/boxart/original/front/11554-1.jpg', 'http://thegamesdb.net/banners/boxart/original/back/11554-1.jpg', 
'http://thegamesdb.net/banners/clearlogo/11554.png', NULL, 5.99, 0.30
),
(
'2Xtreme', '' , 'PS;' , 2 , false , 'Racing;Sports;' , STR_TO_DATE('10/31/1996', '%m/%d/%Y') , 'Sony' , 'SCEA' , 
'http://thegamesdb.net/banners/boxart/original/front/8537-1.png' , NULL , 'http://thegamesdb.net/banners/clearlogo/8537.png' , 
'http://thegamesdb.net/banners/_gameviewcache/publishers/0-sony.png' , 4.49 , 0.00
),
(
'Driver', '' , 'PS;PC;' , 1 , false , 'Action;Racing;' , STR_TO_DATE('07/08/1999', '%m/%d/%Y') , 'Reflections Interactive Limited' , 'GT Interactive' , 
'http://thegamesdb.net/banners/boxart/original/front/1546-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/1546-1.jpg' , 
'http://thegamesdb.net/banners/clearlogo/1546.png' , NULL , 4.99 , 0.25
),
(
'Drive 2', '' , 'PS;' , 2 , false , 'Action;Racing;' , STR_TO_DATE('11/13/2000', '%m/%d/%Y') , 'Reflections Interactive' , 'Infogrames' , 
'http://thegamesdb.net/banners/boxart/original/front/521-2.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/521-1.jpg' , 
'http://thegamesdb.net/banners/clearlogo/521.png' , NULL , 4.99 , 1.00
),
(
'Spyro: Year of the Dragon', 'Spyro: Year of the Dragon is the third installment in the Spyro series and the last Spyro game to be released for the PlayStation. The game was the last Spyro game Insomniac developed; their next title would be Ratchet & Clank for the PlayStation 2. This is the only Spyro game in the PlayStation library to not get released in Japan. Named after the animal of the Chinese zodiac, which was the symbol at the time of the game\'s release, Year of the Dragon follows the titular purple character Spyro as he travels to the "Forgotten Worlds" after 150 magical dragon eggs are stolen from the land of the dragons by an evil sorceress. Players travel across thirty different worlds gathering gems and eggs. Year of the Dragon introduced new characters and minigames to the series, as well as offering improved graphics and music. Upon release, the game sold more than two million units in the United States,and received positive critical response. Reviewers noted the game built on the successful formula of its predecessors.',
 'PS;' , 1 , false , 'Platform;' , STR_TO_DATE('10/23/2000', '%m/%d/%Y') , 'Insomniac Games' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/4986-1.jpg' , 
 'http://thegamesdb.net/banners/boxart/original/back/4986-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-insomniacgames.jpeg' , 5.49 , 0.00
 ),
(
'Jak 3', 'Jak 3 is set in the New World, its time frame placing it around 300 years after the events of the first game. Jak 3 largely focuses on the Wasteland, a large desert only briefly referred to in the previous entry in the series as being completely uninhabited and inhospitable. Spargus City, a large settlement within the Wasteland bordering the ocean, is where the game officially begins, and serves as a hub for the player, where new weapons and upgrades can be earned, and most missions are given out.',
 'PS2;' , 1 , false , 'Action;Platform;Shooter;' , STR_TO_DATE('11/09/2004', '%m/%d/%Y') , 'Naughty Dog' , 'Sony Computer Entertainment' , 
 'http://thegamesdb.net/banners/boxart/original/front/4872-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4872-1.jpg' , NULL , 
 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Naughty_Dog_Logo.png' , 8.49 , 0.00
 ),
(
'Jak and Dexter:The Precursor Legacy', 'Jak and Daxter: The Precursor Legacy offers several collectibles for the player to gather. The main objects are "Power Cells", used to energize machinery for use in reaching new levels. Egg-shaped "Precursor Orbs" function as currency, and can be traded in for Power Cells at several locations in the game, while collecting all seven "Scout Flies" in any level rewards the player with a Power Cell. While Precursor Orbs are present in all Jak and Daxter games, Power Cells would not make a reappearance until Jak 3, where they appear in artifact collecting missions.',
'PS2;PS4;' , 1 , false , 'Action;Platform;' , STR_TO_DATE('12/03/2001', '%m/%d/%Y') , 'Naughty Dog' , 'Sony Computer Entertainment' , 
'http://thegamesdb.net/banners/boxart/original/front/4865-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4865-1.jpg' , 
'http://thegamesdb.net/banners/clearlogo/4865.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Naughty_Dog_Logo.png' , 7.99 , 0.00
),
(
'Jak II', 'The game begins with Jak and Daxter, the protagonists, and Samos, their guardian, watching as Keira, Samos’ daughter and Jak’s love interest, demonstrate the Rift Rider and Precursor Rift Gate that they found in the previous game. When activated, the Rift opens a portal, and a large ominous atmosphere and a monster appear. Jak launches the Rider through the gate, past the monster. Jak and Daxter, separated from Keira and Samos, arrive in the segregated dystopia known as Haven City. They are separated on arrival, and Jak is captured by the city\'s Krimzon Guard. While Jak is imprisoned, he undergoes experiments with Dark Eco under the command of the city\'s leader: Baron Praxis. Jak, along with previous prisoners in the city jail, were experimented on for Operation: Dark Warrior, a project that consisted of injecting prisoners with dark eco in order to give them super-human abilities to be used in Haven City\'s war against animalistic creatures called Metal Heads.' , 'PS2;' , 1 , false , 'Action;Adventure;Platform;Shooter;' , STR_TO_DATE('10/14/2003', '%m/%d/%Y') , 'Naughty Dog' , 'Sony Computer Entertainment' , 'http://thegamesdb.net/banners/boxart/original/front/4867-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4867-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/4867.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Naughty_Dog_Logo.png' , 7.49 , 0.00
),
(
'Jak X : Combat Racing', 'After saving Haven City once again, Jak and Daxter find themselves poisoned forced into competition on the international car-racing circuit by the execution of Krew\'s will. Featuring over a dozen customizable vehicles designed with unique handling characteristics, players will race their whip through 20 tracks in eight different terrain arenas. With an assortment of power-ups available, including projectile weapons, mines, ranged weapons, turbo boosts, shields, and smart bombs, players should have the means necessary to ensure they\'re the first to cross the finish line. The game supports both offline and online multiplayer. Offline multiplayer is the typical two-player split-screen multiplayer. Online multiplayer is playable with up to five other players. Both modes feature the same game types, which are the same as the single player except that human players are replacing the AI.' , 'PS2;' , 1 , false , 'Action;Racing; Shooter;' , STR_TO_DATE('10/18/2005', '%m/%d/%Y') , 'Naughty Dog' , 'Sony Computer Entertainment' , 'http://thegamesdb.net/banners/boxart/original/front/9720-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9720-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Naughty_Dog_Logo.png' , 5.49 , 0.00
),
(
'James Bond 007: Nightfire', 'The game\'s prologue mission starts in Paris, France, with James Bond (voiced by Maxwell Caulfield with the likeness of Pierce Brosnan) helping French Intelligence Operative Dominique Paradis evade a gang chase while chasing a truck with a stolen nuclear weapon, before continuing in his car. After stopping the truck from blowing up the Eiffel Tower, Dominique and James celebrate the new year.' , 'PS2;XBOX;PC;' , 4 , false , 'Shooter;' , STR_TO_DATE('11/18/2002', '%m/%d/%Y') , 'Eurocom' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/4757-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4757-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/4757.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Eurocom.png' , 7.49 , 0.00
),
(
'Juiced', 'The player can choose a wide variety of car modifications, such as visual modifications, performance modifications and more. All of these customization options provide a personalized and unique car to suit the player\’s needs. The gameplay offered to the player includes a career mode, sprint, race, solo, cruise, and a new show-off mode where the player does tricks with his or her car to keep the crowd entertained.' , 'PS2;XBOX;PC;' , 1 , false , 'Racing;' , STR_TO_DATE('06/15/2005', '%m/%d/%Y') , 'Juice Games' , 'THQ' , 'http://thegamesdb.net/banners/boxart/original/front/4860-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4860-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-logo_USGames.jpg' , 5.99 , 0.00
),
(
'Killzone', 'The game is set in an era of space colonization where the Helghast Empire has recovered from its defeat in the First Helghan War and launched a blitzkrieg against the outer Interplanetary Strategic Alliance (I.S.A.) colony planet Vekta. Vekta\'s orbital Strategic Defense (S.D.) platforms failed during the initial assault, allowing the Helghast to land swarms of soldiers onto the surface and making it all the more difficult for the outnumbered I.S.A. forces. In the game, the Helghast are a faction of human descendants who colonized the planet Helghan many generations ago. The planet\'s harsh environment forced the Helghast to adapt and mutate so much that they can no longer be considered human.' , 'PS2;' , 1 , false , 'Shooter;' , STR_TO_DATE('11/02/2004', '%m/%d/%Y') , 'Guerrilla Games' , 'Sony Computer Entertainment Europe' , 'http://thegamesdb.net/banners/boxart/original/front/35-2.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/35-1.jpg' , NULL , NULL , 7.99 , 0.00
),
(
'LEGO Indiana Jones: The Original Adventures', 'In LEGO Indiana Jones: The Original Adventures the players get to explore the Indiana Jones universe with "LEGO-fied" characters. The game focuses on the three original films: Raiders of the Lost Ark, Indiana Jones and the Temple of Doom, and Indiana Jones and the Last Crusade, each film consisting of six separate chapters retelling the stories in a humorous, light-hearted way that tones down the violence while removing some of the more overt religious and political references found in the film.' ,
'PS2;PS3;XBOX360;PC;' , 2 , true , 'Action;Platform;' , STR_TO_DATE('06/03/2008', '%m/%d/%Y') , 'Traveller\'s Tales' , 'LucasArts' , 'http://thegamesdb.net/banners/boxart/original/front/10831-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/10831-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/10831.png' , NULL , 5.99 , 0.50
),
(
'Lego Star Wars: The Video Game', 'Gameplay in Lego Star Wars is geared towards family play, and as such does not feature a game over scenario. Given a specific set of characters in each scenario, based on a scene from each of the movies, up to two players can control them, using their different abilities. By walking up to another friendly character, the player can switch control over to that character, which is necessary for using some of their abilities to complete puzzles. Studs can be found by finding them, smashing or using the force on certain objects, or defeating enemies. Players will lose studs however if their character is destroyed (as opposed to losing lives). These studs can be spent on unlocking new characters for Free Play mode.',
'PS2;XBOX;PC;', 2 , true , 'Action;Platform;' , STR_TO_DATE('03/29/2005', '%m/%d/%Y') , 'Traveller\'s Tales' , 'Eidos' , 
'http://thegamesdb.net/banners/boxart/original/front/4840-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4840-1.jpg' , 
'http://thegamesdb.net/banners/clearlogo/4840.png' , NULL , 5.99 , 0.00
),


(
'Lego Star Wars II: The Original Trilogy', 'Lego Star Wars II is based on A New Hope, The Empire Strikes Back and Return of the Jedi. The game comically retells the trilogy\'s events using cut scenes without dialogue. The player assumes the roles of the films\' characters, each of which possess specific weapons and abilities. At any time, a second player can join the game by activating a second controller.' , 
'PS2;XBOX;XBOX360;PC' , 2 , true , 'Action;Platform;' , STR_TO_DATE('09/11/2006', '%m/%d/%Y') , 'Traveller\'s Tales' , 'LucasArts' , 
'http://thegamesdb.net/banners/boxart/original/front/4845-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4845-1.jpg' , 
'http://thegamesdb.net/banners/clearlogo/4845.png' , NULL , 7.00 , 0.00
),
('Medal of Honor: Rising Sun', 'The game starts at Pearl Harbor where corporal Joseph \'Joe\' Griffin wakes up in his bunk on the USS California (BB-44) during the attack. Joe then makes his way to the topside and aids in shooting down Japanese planes. A few minutes later, he is blown from the ship and lands in the water, where a PT boat carrying Jack \'Gunny\' Lawton, Frank Spinneli, and Silas Whitfield. Joe then shoots down more planes and also aids the USS Nevada (BB-36) to escape the harbor. Joe is then sent to the Philippines to destroy a bridge, and he meets his brother Donnie. Donnie is unable to escape the islands because his tank was overwhelmed by Japanese troops, forcing Joe to leave without him. Joe then goes to Guadalcanal at night to take over an airbase. Days later, the airfield is still taking heavy artillery fire, so Gunny assigns Joe and two other marines to destroy the artillery nicknamed \'Pistol Pete\'.' , 'PS2;XBOX;' , 2 , true , 'Shooter;' , STR_TO_DATE('11/11/2003', '%m/%d/%Y') , 'Electronic Arts' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/4267-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4267-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/4267.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png' , 9.00 , 0.00),
('Midnight Club 3:DUB Edition', 'Midnight Club 3: DUB Edition is a racing game, developed by Rockstar San Diego and published by Rockstar Games, and is the third game in the Midnight Club series. Like previous installments in the series, the game is an arcade-style racer and focuses on wild, high-speed racing, rather than realistic physics and driving characteristics. The name derived from a partnership between Rockstar and DUB Magazine, which features heavily in the game in the form of DUB-sponsored races and DUB-customized vehicles as prizes.' , 'PS2;XBOX;' , 2 , false , 'Racing;' , STR_TO_DATE('03/13/2006', '%m/%d/%Y') , 'Rockstar' , 'Rockstar' , 'http://thegamesdb.net/banners/boxart/original/front/4825-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4825-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/56-folder.png' , 7.00 , 0.00),
('Midnight Club 3:DUB Edition : Remix', 'Midnight Club 3: DUB Edition is a racing game, developed by Rockstar San Diego and published by Rockstar Games, and is the third game in the Midnight Club series. Like previous installments in the series, the game is an arcade-style racer and focuses on wild, high-speed racing, rather than realistic physics and driving characteristics. The name derived from a partnership between Rockstar and DUB Magazine, which features heavily in the game in the form of DUB-sponsored races and DUB-customized vehicles as prizes.' , 'PS2;XBOX;' , 2 , false , 'Racing;' , STR_TO_DATE('12/03/2006', '%m/%d/%Y') , 'Rockstar' , 'Rockstar' , 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Midnight_club_3_dub_edition_remix_cover.jpg/256px-Midnight_club_3_dub_edition_remix_cover.jpg' , NULL , NULL , NULL , 10.00 , 0.00),
('Need for Speed:Underground', 'Need For Speed: Underground is the seventh game in the long running Need For Speed racing series. Underground revolves around illegal nighttime street racing with heavily modified import cars and has been greatly influenced by the movie "The Fast And The Furious" and its sequel.. Players get the chance to build their own racing machine almost from ground up, with hundreds or real licensed parts and lots of licensed cars, including the Mazda RX-7 and the Nissan Skyline GT-R. The game also features over 100 single player races and a hiphop/hardrock soundtrack including artists such as Mystikal, Rob Zombie and The Crystal Method.' , 'PS2;XBOX;PC;' , 1 , false , 'Racing;' , STR_TO_DATE('11/17/2003', '%m/%d/%Y') , 'Electronic Arts' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/5396-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/5396-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/5396.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png' , 6.00 , 0.00),
('NHL 08', '' , 'PS2;PS3;XBOX360;PC;' , 2 , true , 'Sports;' , STR_TO_DATE('09/11/2007', '%m/%d/%Y') , 'Electronic Arts' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/16035-1.jpg' , NULL , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png' , 8.00 , 0.00),
('Prince of Persia: The Sands of Time', 'Prince of Persia: The Sands of Time is a 3D platformer which focuses on acrobatics and agility. Throughout much of the game, the player must attempt to traverse the palace by running across walls, ascending or descending chasms by jumping back and forth between walls, avoiding traps, climbing structures and jumping from platform to platform, making other types of well-timed leaps, solving puzzles, and using discovered objects to progress.' , 'PS2;XBOX;PC;' , 1 , false , 'Platform;' , STR_TO_DATE('11/21/2003', '%m/%d/%Y') , 'Ubisoft' , 'Ubisoft' , 'http://thegamesdb.net/banners/boxart/original/front/4805-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4805-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/4805.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/72-folder.png' , 8.00 , 0.00),
('Prince of Persia: The Two Thrones', 'Prince of Persia: The Two Thrones follows the second ending of Prince of Persia: Warrior Within, in which the Prince kills the Dahaka, essentially saving Kaileena. The game opens with the Prince and Kaileena about to sail into Babylon\'s port. Kaileena offers narration of the events passed and the story following, similar to the Prince\'s role as both protagonist and narrator in The Sands of Time.' , 'PS2;XBOX;PC;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('12/01/2005', '%m/%d/%Y') , 'Ubisoft' ,'Ubisoft' , 'http://thegamesdb.net/banners/boxart/original/front/4803-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4803-1.jpg' , NULL , NULL , 9.00 , 0.00),
('Ratchet & Clank', 'Ratchet & Clank is a platform/adventure game in a similar vein to the 3D versions of the Rayman, Sonic, Mario, or other games. It involves the two protagonists Ratchet, a furry alien creature, and Clank, a nerdy little robot, going on a quest to find Captain Qwark and ultimately to help save the galaxy. Ratchet & Clank includes many of the best features of previous similar games, but makes itself unique in a number of ways. Firstly each of the game\'s levels are huge sweeping vistas with extremely detailed buildings which are visible at all times (i.e. there is no distance fog). This means that a building on the horizon is not just a "backdrop"; in all likelihood Ratchet will be exploring it in a few moments time.' , 'PS2;PS3;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('11/04/2002', '%m/%d/%Y') , 'Insomniac Games' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/7797-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/7797-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/7797.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-insomniacgames.jpeg' , 15.00 , 0.00),
('Ratchet & Clank: Going Commando', 'Ratchet and Clank return for a new intergalactic adventure, one laced with role-playing game elements, in this follow-up to 2002\'s hit platform game starring the cat-like Ratchet and his robotic companion, Clank. Players can now watch as Ratchet becomes stronger as he gains experience points and acquires upgradeable weapons and five levels of armor. Players will also earn cash by competing in hovercraft races, fighting in gladiatorial arenas, and engaging in space combat. A total of 20 weapons and gadgets are available to blast enemies, including the lava gun that spews magma on unsuspecting foes. The action takes place on 20 all-new planets with areas nearly one-and-a-half times larger than those found in the first game.' , 'PS2;PS3;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('11/11/2003', '%m/%d/%Y') , 'Insomniac Games' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/13150-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/13150-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/13150.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-insomniacgames.jpeg' , 12.00 , 0.00),
('Ratchet & Clank: Up Your Arsenal', 'After word spreads of Ratchet and Clank\'s recent conquest in Ratchet & Clank: Going Commando, Clank finds himself recognized as an interstellar robot of mystery and intrigue after starring in his own television series, Secret Agent Clank. While Ratchet is dismayed by his new sidekick status, the feelings are put aside when the twosome is called together by the Galactic President to bring peace to the universe. They find themselves traveling back to Planet Veldin to battle Dr. Nefarious, a robotic super villain who has devised a diabolical scheme to wipe out all organic life in the galaxy.' , 'PS2;PS3;' , 4 , true , 'Action;Adventure;' , STR_TO_DATE('11/17/2004', '%m/%d/%Y') , 'Insomniac Games' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/7992-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/7992-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/7992.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-insomniacgames.jpeg' , 12.00 , 0.00),
('Ratchet:Deadlocked', 'Ratchet: Deadlocked is the fourth game in the Ratchet & Clank series by Insomniac Games. Deadlocked is different in its counterparts in that it focuses more on shooting than platforming and puzzle elements. The game allows you to use two bots to fight along side you, which can be upgraded over time with better weapons and firepower. You can team up with a friend (who can control various bots) against the enemies and mini-games found in this game. The storyline involves Ratchet and Clank, along with Al, being kidnapped and forced to compete in a underground reality show called "DreadZone" run by the media mogul Gleeman Vox on the outer fringes of the galaxy. There are 10 total weapons in the game, significantly less than the other games. However, modding these weapons is more emphasized than before, with different kinds of Alpha and Omega mods. Omega mods can be used on any weapon, and range from the freeze mod to the magma mod.' , 'PS2;PS3;' , 4 , true , 'Action;Adventure;' , STR_TO_DATE('10/25/2005', '%m/%d/%Y') , 'Insomniac Games' ,'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/9781-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9781-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/9781.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-insomniacgames.jpeg' , 10.00 , 0.00),
('Red Faction', 'Red Faction takes place on Mars around the year 2070. Earth’s minerals are being depleted and humans need more of them to survive. The vast Ultor Corporation runs the mining operation on Mars. The living conditions are deplorable, human rights for the miners are few and a disease called "The Plague" is running rampant throughout the colony with no known antidote available - predominantly within the confines of the mine complex. Parker, a downtrodden miner, came to Mars to make a new start in his life - taken in by the promises and advantages Ultor has to offer in the mines of Mars.' , 'PS2;PC;' , 2 , true , 'Shooter;' , STR_TO_DATE('05/21/2001', '%m/%d/%Y') , 'Volition' , 'THQ' , 'http://thegamesdb.net/banners/boxart/original/front/4799-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4799-1.jpg' , NULL , NULL , 8.00 , 0.00),
('Rock Band', 'Rock Band allows gamers to perform music from the world\'s biggest rock artists with their friends as a virtual band using drum, bass/lead guitar and microphone peripherals, in addition to offering deep online connectivity. Built on unprecedented deals with the world\'s biggest record labels and music publishers, the music featured in Rock Band spans all genres of rock and includes many of the master recordings from the biggest songs and artists of all time.' , 'PS2;PS3;XBOX;', 4 , true , 'Music;' , STR_TO_DATE('12/18/2007', '%m/%d/%Y') , 'Harmonix' , 'MTV' , 'http://thegamesdb.net/banners/boxart/original/front/19757-1.jpg' , NULL , NULL , NULL , 6.00 , 0.00),
('Sly 2:Band of Thieves', 'Thief and raccoon Sly Cooper returns in a new cel-shaded platforming adventure wherein he forms a band of thieves with Bentley the turtle and Murray the purple, hippo-like creature, which each have their own role within the game. Sly is the fastest, most agile member of the band of thieves and still is the character you play with the most. But certain missions require the special abilities of Bentley, who is smart and can drop bombs, as well shoot enemies from a distance. Other missions require the muscles of Murray, who can lift nearly everything, including enemies. The main goal of the game is the retrieval of a number of clockwork pieces from different locations around the world. Each theft has to be prepared with a number of sub-missions which have to be completed before the \'real thing\' can begin.' , 'PS2;PS3;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('09/14/2004', '%m/%d/%Y') , 'Sucker Punch' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/9813-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9813-1.jpg' , NULL , NULL , 10.00 , 0.00),
('Sly 3:Honor Among Thieves', 'Sly and the gang is back in this third outing of Sly Raccoon-series. This time, the story takes the boys (Sly, Bentley and Murray) to the fortress that houses the treasures of Sly\'s family. Although they are still weary from the adventures in the previous game, they have to get up and face the new threat that could mean the end of Sly\'s business and the loss of his family heritage. The game itself is a lot like the previous games: Sly sneaks, jumps, and swings himself around the levels, collecting various items, defeating bad guys and ultimately taking on the boss character. The other members of the gang step in on the action once in a while but the Sly centric sections are the main focus of the game. If you like games that had many things to do, this sneak-em-up/platform/action/adventure/puzzle game is for you.' , 'PS2;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('09/26/2005', '%m/%d/%Y') , 'Sucker Punch' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/9814-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9814-1.jpg' , NULL , NULL , 9.00 , 0.00),
('Sly Cooper and the Thievius Raccoonus', 'Sly Cooper is the latest in a long line of master thieves. When he was a kit, a gang called the Fiendish Five killed his family and divided up their book on the art of thieving: the Thievius Raccoonus. Sly must defeat all the members of the gang to recover the book while evading Carmelita Fox, a police officer chasing him around the world to apprehend him. This game is divided into five worlds, each themed around a particular part of the world and the villain headquartered there. Most worlds are structured as a central hub with entrances to numerous individual levels. Each of the levels has a primary goals which earns you a key. You must collect all the keys in the world to fight the world\'s boss. Many of the levels have a platformer structure. The objective of these worlds is to reach the location of the key.' , 'PS2;PS3;' , 1 , false , 'Action;Adventure;' , STR_TO_DATE('09/26/2002', '%m/%d/%Y') , 'Sucker Punch' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/9815-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9815-1.jpg' , NULL , NULL , 11.00 , 0.00),
('Spyro: Enter the Dragonfly', 'Spyro the dragon is back yet again with his trusted dragonfly Sparx. After the end of the last game, Spyro and his friends Hunter, Bianca, Bentley, the Professor and Shiela, had a great time at the Year of the Dragon festival at Dragon Shores. But something goes horribly wrong.!!' , 'PS2;', 1 , false , 'Platform;' , STR_TO_DATE('11/15/2002', '%m/%d/%Y') , 'Check Six' , 'Universal Interactive' , 'http://thegamesdb.net/banners/boxart/original/front/9823-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9823-1.jpg' , NULL , NULL , 6.00 , 0.00),
('Star Wars: Battlefront', 'Star Wars: Battlefront encompasses battles between four main factions from both the original and prequel trilogies: the Galactic Republic and the Confederacy of Independent Systems (CIS) of the prequel era, and the Rebel Alliance and Galactic Empire of the classic trilogy. However, factions can only play their historical adversary; there cannot be any Rebels vs. Separatists or Clones vs. Empire fights. In each faction, five different classes of characters become available. Four of the classes are similar for each faction: a basic infantry soldier (a Super battle droid for the CIS), heavy weapons soldier, pilot and sniper.' , 'PS2;XBOX;PC;' , 2 , true , 'Shooter;' , STR_TO_DATE('09/20/2004', '%m/%d/%Y') , 'Pandemic' , 'LucasArts' , 'http://thegamesdb.net/banners/boxart/original/front/4781-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4781-1.jpg' , NULL , NULL , 7.00 , 0.00),
('Star Wars: Battlefront II', 'Battlefront II features a more narrative-based campaign, retelling portions of the Star Wars story from the point of view of a veteran Imperial stormtrooper, reminiscing about his tour of duty in service of both the Galactic Republic and as part of the Galactic Empire. Gameplay additions over Battlefront include the use of Jedi, additional game modes, and objective-based space battles. Two players can play splitscreen co-op throughout the story campaign or a strategic Galactic Conquest campaign.There is also a "comp stomp" configuration that supports 2 players offline, 2 players splitscreen online, or up to 16 players online.' , 'PS2;XBOX;XBOX1;PC;' , 2 , true , 'Shooter;' , STR_TO_DATE('11/01/2005', '%m/%d/%Y') , 'Pandemic' , 'LucasArts' , 'http://thegamesdb.net/banners/boxart/original/front/4780-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4780-1.jpg' , NULL , NULL , 8.00 , 0.00),
('Starsky & Hutch', 'Starsky & Hutch is an arcade racing game based on the popular TV series from the 70s, released to tie in with the film. The game includes 18 missions, each based on an episode of the TV show and introduced by Antonio \'Huggy Bear\' Fargas. There is also a free roaming mode, in which the player explores the GTA-esque environment looking for action and trouble. Like the film, the game does not entirely play it straight. Starsky & Hutch are actually shooting a TV show, and the scoring for each mission reflects how ratings-friendly your driving is. You are awarded gold, silver or bronze medals for each mission depending on performance, and must get at least 1 gold and 2 silvers on season 1 for a second season to be commissioned, and 3 golds and 2 silvers in season 2 for there to be a third for you to play through. The overall goal in each mission is usually to chase and destroy a criminal\'s car.' , 'PS2;XBOX;' , 1 , false , 'Action;Shooter;' , STR_TO_DATE('09/09/2003', '%m/%d/%Y') , 'Mind\'s Eye' , 'Mind\'s Eye' , 'http://thegamesdb.net/banners/boxart/original/front/9797-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/9797-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/9797.png' , NULL , 5.00 , 0.00),
('Stuntman Ignition', 'Stuntman: Ignition is the next installment in the Stuntman franchise. The game plunges gamers into the adrenaline-fueled role of a Hollywood stunt driver, challenging them to pull off the most breathtaking, death-defying stunts ever filmed. Players showcase their skills in a wide variety of big-budget action films, commercial shoots and tournaments while commanding more than 25 unique vehicles, including exotic sports cars, motorcycles and hovercraft.' , 'PS2;' , 1 , false , 'Racing;' , STR_TO_DATE('08/28/2007', '%m/%d/%Y') , 'Paradigm Entertainment' , 'THQ' , 'http://thegamesdb.net/banners/boxart/original/front/36023-1.jpg' , NULL , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/1-Paradigm_entertainment.png' , 9.00 , 0.00),
('The Simpsons: Hit & Run', 'The Simpsons: Hit & Run can be best described as Grand Theft Auto in Springfield. The player takes on the role of Homer, Marge, Bart, Lisa or Apu and try to uncover a mystery surrounding mechanical bees that are taking over Springfield, mysterious vans, and cola that can control the minds of those who drink it. Like GTA, the game follows a linear-based path through fifty plus missions. The player will have to chase cars and find out where they\'re headed, grab all the spilling cola cans before people can drink them, and chasing down villains before they get away. Throughout the course of the game, the player can unlock tons of rewards by completing missions in a set amount of time or performing outstanding stunts.' , 'PS2;XBOX;PC;' , 4 , false , 'Action;Racing;' , STR_TO_DATE('09/16/2003', '%m/%d/%Y') , 'Radical Entertainment' , 'Fox' , 'http://thegamesdb.net/banners/boxart/original/front/5420-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/5420-1.jpg' ,'http://thegamesdb.net/banners/clearlogo/5420.png' , NULL , 6.00 , 0.00),
('Tony Hawk\'s Pro Skater 3', 'This game saw the introduction of the revert, a trick that enabled vert combos to be tied together with a manual, by tapping a button when landing in a quarterpipe. This allowed for much longer combos than in the previous two games, where landing in a quarterpipe would finish a combo. The game also added hidden combos. These were variations on standard tricks that could be performed as grab, flip, lip, or grind tricks. For example, double-tapping the kickflip button would, naturally, make the character perform a double kickflip.' , 'PS;PS2;XBOX;PC;' , 1 , false , 'Sports;' , STR_TO_DATE('10/28/2001', '%m/%d/%Y') , 'Neversoft' , 'Activision' , 'http://thegamesdb.net/banners/boxart/original/front/4772-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4772-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Neversoft.png' , 7.00 , 0.00),
('Black', 'Black takes place in Chechnya (Southern Russia). The protagonist is a black ops soldier named Sergeant First Class Jack Kellar (portrayed by Marty Papazian). Kellar tells most of the story in first-person at an interrogation four days after the events in the story begin. Kellar is an inadequately disciplined member of a CIA black ops group and a veteran of several conflicts including Guatemala, Colombia, Iran and Croatia. The unknown interrogator (portrayed by Paul Pape) questions Kellar about an arms smuggling and terrorist operation called the Seventh Wave. Seventh Wave have been responsible for a number of terrorist attacks. Kellar is told that, unless he co-operates, he and his actions will be declassified, he will be dishonorably discharged and imprisoned for life. Though initially resistant, Kellar at last agrees to tell his story.' , 'PS2;XBOX;' , 1 , false , 'Action;Shooter;' , STR_TO_DATE('02/28/2006', '%m/%d/%Y') , 'Electronic Arts' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/3942-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/3942-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png' , 10.00 , 0.00),
('Bully', 'Bully is a subtle sandbox game set in a school environment. The player takes control of teenage rebel James "Jimmy" Hopkins, who from the opening cutscene is revealed to be a difficult student with a disruptive background. The game concerns the events that follow Jimmy being dropped off at Bullworth Academy, a fictional New England boarding school. The player is free to explore the school campus in the beginning and, later on in the game, the town, or to complete the main missions. The game makes extensive use of minigames. Some are used to earn money, others to improve Jimmy\'s abilities or get new items. School classes themselves are done in the form of minigames, broken into five levels of increasing difficulty. Each completed class brings a benefit to gameplay. English, as an example, is a word scramble minigame, and as Jimmy does well in this minigame, he learns various language-skills, such as the ability to apologize to police for small crimes.' , 'PS2;' , 1 , false , 'Action;' , STR_TO_DATE('10/17/2006', '%m/%d/%Y') , 'Rockstar' , 'Rockstar' , 'http://thegamesdb.net/banners/boxart/original/front/3931-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/3931-1.jpg' , 'http://thegamesdb.net/banners/clearlogo/3931.png' , 'http://thegamesdb.net/banners/_gameviewcache/publishers/56-folder.png' , 8.00 , 0.00),
('Burnout 3 Takedown', 'Burnout 3: Takedown is a racing game which encourages aggressive driving and lets you use your vehicle to smash your way to the finish line by taking out your rivals and causing massive multi-car pileups. The more cars you take out, damage you inflict, the more events and cars you can unlock. Burnout 3 also has a "crash" mode which puts your vehicle at a variety of traffic junctions jam-packed with moving vehicles and pickups to see just how much monetary damage you can inflict. Burnout 3: Takedown continues the racing series with more cars, more tracks, a more detailed crash engine, and a multitude of new gameplay modes for single players, multiple players on one system, and online play.' , 'PS2;XBOX;' , 2 , false , 'Racing;' , STR_TO_DATE('09/07/2004', '%m/%d/%Y') , 'Criterion Studios' , 'Electronic Arts' , 'http://thegamesdb.net/banners/boxart/original/front/4158-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4158-1.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-CriterionGames.png' , 10.00 , 0.00),
('Call of Duty 2:Big Red One', 'The game follows the U.S. Army\'s 1st Infantry Division (the "Big Red One") from the sands of Africa to the rolling hillsides of Sicily and the beaches of Normandy and to the heart of Germany. On the way, new weapons, vehicles, and aircraft will be unlocked. The player gets to play with two American soldiers during World War II, as an aircraft gunner and an infantryman.' , 'PS2;XBOX;' , 1 , false , 'Shooter;' , STR_TO_DATE('11/01/2005', '%m/%d/%Y') , 'Grey Matter' , 'Activision' , 'http://thegamesdb.net/banners/boxart/original/front/4270-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/4270-1.jpg' , NULL , NULL , 6.00 , 0.00),
('Chessmaster', '' , 'PS2;' , 2 , false , 'Strategy;' , NULL , NULL , NULL , 'http://thegamesdb.net/banners/boxart/original/front/43008-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/43008-1.jpg' , NULL , NULL , 3.00 , 1.00),
('Corvette', 'Corvette lets you race a variety of Corvettes on the open road or in super speedways. The game includes more than 120 production Corvette models from 1953 to 2003, plus show and race cars. Choose a car, official car color, and a driver, and then race on tracks or an obstacle-filled Route 66. Upgrade your car\'s engine and suspension for more realistic physics. In Heritage mode, you can take a trip through Corvette history and test-drive any stock production Corvette.' , 'PS2;XBOX;' , 2 , false , 'Racing;' , NULL , NULL , NULL , 'http://thegamesdb.net/banners/boxart/original/front/21567-1.jpg' , NULL , NULL , NULL , 6.00 , 0.00),
('DT Racer', 'Extreme tuner racing just hit a whole new level of no holds barred racing. DT Racer drops you on to 22 of the slickest tracks around the globe. Completely fine tune every inch of your car\'s handling and performance with unlimited customization. And when you are done, put your foot to the floor and show them what you\'ve got!' , 'PS2;' , 2 , false , 'Racing;' , STR_TO_DATE('09/26/2005', '%m/%d/%Y') , 'Axis Entertainment' , 'XS Games' , 'http://thegamesdb.net/banners/boxart/original/front/13649-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/13649-1.jpg' , NULL , NULL , 5.00 , 0.00),
('Ford Racing 3', 'Experience the thrill of racing 55 of Ford\'s most prominent driving machines from the Model T to the 2005 Mustang GT in Empire Interactive\'s Ford Racing 3. Test your driving skill on 26 meticulously detailed tracks with interactive scenery from locations like the snow-packed mountains of Europe to the rain forests of South America. Take part in more than 20 hours of intense automobile action while competing in 11 challenging race types such as Boost, Overtake, and Relay while unlocking a huge range of game modes, tracks, and vehicles along the way. Players can even earn up to 14 different championships and contend with their friends in split-screen two-player head-to-head. Also available for Windows PC and Xbox.' , 'PS2;XBOX;PC;' , 2 , false , 'Racing;' , STR_TO_DATE('03/22/2005', '%m/%d/%Y') , 'Razorworks' , '2K Games' , 'http://thegamesdb.net/banners/boxart/original/front/27230-1.jpg' , NULL , NULL , NULL , 4.00 , 0.00),
('God of War', 'This action/adventure/combat game makes powerful use of the darkly imaginative world of Ancient Greek mythology, where the realms of the mortal and the divine collide in a pervasive atmosphere of brute force and violence. Playing as Kratos, throughout the game players will wield double blades bound to his body by long chains, weapons symbolic of this vicious world to which he is bound and the fate from which he seeks to escape. Featuring an hour of cinematic sequences and a deep combat system incorporating context-sensitive actions and an extensive range of combos, GOD OF WAR takes players through various environments that will have them fighting fierce enemies, swinging on ropes, scaling mountain cliffs, swimming through rivers and sliding down zip lines. The result is a unique and thrilling adventure through Greek mythology.' , 'PS2;' , 1 , false , 'Action;Platform;' , STR_TO_DATE('03/22/2005', '%m/%d/%Y') , 'SCE Santa Monica Studio' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/26-2.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/26-2.jpg' , NULL , 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-SCE_Santa_Monica_Studio_logo.png' , 8.00 , 0.00),
('Gran Turismo 4', 'GT4 continues in its predecessors\' footsteps by offering an extremely large list of cars; the PAL version features 721 cars from 80 manufacturers. Players now accumulate points by winning races in the normal first-person driving mode, called A-Spec mode. Each race event can yield up to a maximum of 200 A-Spec points. Generally, a win using a car with less of an advantage over the AI opponents is worth more points. Points can only be won once, so to win further points from a previously-won event, it must be re-won using a car with less of an advantage over the AI. There are also the 34 Missions which can yield 250 points each. Despite this, A-Spec points are experience points, not money.' , 'PS2;' , 4 , false , 'Racing;' , STR_TO_DATE('02/22/2005', '%m/%d/%Y') , 'Polyphony Digital' , 'Sony' , 'http://thegamesdb.net/banners/boxart/original/front/3929-1.jpg' , 'http://thegamesdb.net/banners/boxart/original/back/3929-2.jpg' , NULL , NULL , 7.00 , 0.00)

;
